### ISSUE TITLE
Incompatible with prettier 3.1

### ISSUE THREAD

**Issue by cunneen** [Beaglefoot/prettier-plugin-awk#22]
Firstly, thank you *so* much for contributing this to the community.

I had problems when following the instructions in the README, and eventually figured out that this plugin doesn't work with the latest version of prettier which gets installed by default.

When running:

```bash
npx prettier --write ./SelfClosingTagSearch.awk                    
```
I encountered the following error:

```ini
SelfClosingTagSearch.awk
[error] SelfClosingTagSearch.awk: InvalidDocError: Unexpected doc.type 'concat'.
[error] Expected it to be 'cursor', 'indent', 'align', 'trim', 'group', 'fill', 'if-break', 'indent-if-break', 'line-suffix', 'line-suffix-boundary', 'line', 'label', or 'break-parent'.
[error]     at traverseDoc (file:///Users/user/.nvm/versions/node/v18.18.2/lib/node_modules/prettier/index.mjs:17406:13)
```

To get it working temporarily I did the following:

1. Uninstalled `prettier` and `prettier-plugin-awk` from my local project: 
    ```bash
    npm uninstall prettier prettier-plugin-awk # or 'yarn uninstall prettier prettier-plugin-awk'
    ``` 

2. I also had installed `prettier` and `prettier-plugin-awk` globally (while trying to get this to work), so I uninstalled both of those:
    ```bash
    npm uninstall -g prettier-plugin-awk prettier
    ```
3. I added a `@2` to `prettier` in the install command when I reinstalled locally into my project's `node_modules` :

    ```bash
    npm add --save-dev prettier@2 prettier-plugin-awk
    ```
    
It now works nicely:

```bash
npx prettier --write ./SelfClosingTagSearch.awk 
# (outputs: "SelfClosingTagSearch.awk 9ms")
```

**Comment by Beaglefoot** [comment]
Thanks for highlighting this! I updated the README to avoid further confusion.

**Comment by jmdevin** [comment]
@Beaglefoot, will this plugin support prettier 3 in the future?

**Comment by Beaglefoot** [comment]
@jmdevin I don't think so. Nowadays I'm not so enthusiastic about awk. Although I plan to fix some parser bugs so you can see updates in the future.

**Comment by Monty** [comment]
Sorry you are not so enthusiastic about awk anymore. I realize it's no longer a popular language. Since I still use awk a lot, I submitted a PR last week that makes the  plugin support prettier 3.

[Update to prettier 3.x and Node 24 via web-tree-sitter (WASM)](https://github.com/Beaglefoot/prettier-plugin-awk/pull/27)


I hope you have time to take a quick look.

Thanks again for creating the plugin in the first place!

**Comment by Beaglefoot** [comment]
Hey @Monty, thanks for contributing! I have PR review on my todo list, but it's not alone there...

**Comment by Monty** [comment]
Thanks! I'm not in a hurry, I've been using it for a while but wasn't sure if anyone else would ever need it.

The fix was to replace `tree-sitter` with `web-tree-sitter` (WASM). The `.wasm` file was already bundled in your `tree-sitter-awk` 0.7.2, so no grammar changes were needed. WASM has no ABI dependency and should work on all future Node versions.
